<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Catalogo.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../SharedKernel/SharedKernel.csproj" />
  </ItemGroup>

</Project>
